# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 09:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tweets2cash.base.db.models.fields.json
import tweets2cash.base.utils.colors
import tweets2cash.base.utils.time
import tweets2cash.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('full_name', models.CharField(blank=True, max_length=256, verbose_name='full name')),
                ('color', models.CharField(blank=True, default=tweets2cash.base.utils.colors.generate_random_hex_color, max_length=9, verbose_name='color')),
                ('bio', models.TextField(blank=True, default='', verbose_name='biography')),
                ('photo', models.FileField(blank=True, max_length=500, null=True, upload_to=tweets2cash.users.models.get_user_file_path, verbose_name='photo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('lang', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='default language')),
                ('theme', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='default theme')),
                ('timezone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='default timezone')),
                ('colorize_tags', models.BooleanField(default=False, verbose_name='colorize tags')),
                ('token', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='token')),
                ('email_token', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='email token')),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='new email address')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
